### PR TITLE
Fix NPE when loading maps with terraintypes

### PR DESCRIPTION
**Pull request by LTI2000**
Simple null pointer check, enable loading of Tiled maps containing terraintpyes

### CODE REVIEW

**Comment by nguillaumin** [comment]
Cool thanks. Would you mind add a bullet point in the `CHANGELOG.md` for this? Thanks.

**Comment by LTI2000** [comment]
Ok, I've added the bullet in CHANGELOG.md

**Comment by nguillaumin** [comment]
Thanks!

**Comment by LTI2000** [comment]
Thanks to you!

**Pull request merged**
